---
teamcity_agent_user: agent-tc
teamcity_agent_group: agent-tc
teamcity_agent_home: /opt/teamcity-agent
teamcity_agent_name: "{{ inventory_hostname }}"

teamcity_agent_work_dir: "{{ teamcity_agent_home }}/work"
teamcity_agent_temp_dir: "{{ teamcity_agent_home }}/temp"
teamcity_agent_system_dir: "{{ teamcity_agent_home }}/system"
teamcity_agent_conf_dir: "{{ teamcity_agent_home }}/conf"

teamcity_agent_java_package_debian: openjdk-21-jdk
teamcity_agent_java_package_redhat: java-21-openjdk-devel
teamcity_agent_download_url: "{{ teamcity_server_url }}/update/buildAgent.zip"
