---
all:
  children:
    teamcity:
      children:
        teamcity_server:
          hosts:
            tc-server-01:
              ansible_host: 10.10.10.10
              teamcity_server_compose_dir: /home/docker/teamcity
        teamcity_agents:
          hosts:
            tc-agent-01:
              ansible_host: 10.10.10.11
              teamcity_agent_name: tc-agent-01
